# Generated by Django 5.0.6 on 2024-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='whatsapp_icons/')),
                ('alt_text', models.CharField(max_length=255)),
            ],
        ),
    ]
