# Generated by Django 5.0.6 on 2024-06-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default=1234567890, max_length=20),
            preserve_default=False,
        ),
    ]
